import { User, Email, Thread, Label } from '@/types'

export const mockCurrentUser: User = {
  id: '1',
  email: 'john@email.com',
  fullName: 'John Doe',
  avatar: 'JD',
}

export const mockUsers: User[] = [
  mockCurrentUser,
  {
    id: '2',
    email: 'sarah.mitchell@company.com',
    fullName: 'Sarah Mitchell',
    avatar: 'SM',
  },
  {
    id: '3',
    email: 'james.wilson@company.com',
    fullName: 'James Wilson',
    avatar: 'JW',
  },
  {
    id: '4',
    email: 'emily.johnson@company.com',
    fullName: 'Emily Johnson',
    avatar: 'EJ',
  },
  {
    id: '5',
    email: 'michael.brown@company.com',
    fullName: 'Michael Brown',
    avatar: 'MB',
  },
  {
    id: '6',
    email: 'laura.thompson@company.com',
    fullName: 'Laura Thompson',
    avatar: 'LT',
  },
]

export const mockLabels: Label[] = [
  { id: '1', name: 'Important', color: '#ef4444', count: 5 },
  { id: '2', name: 'Work', color: '#2563eb', count: 12 },
  { id: '3', name: 'Personal', color: '#10b981', count: 8 },
]

const now = new Date()

export const mockEmails: Email[] = [
  {
    id: '1',
    threadId: 'thread-1',
    from: mockUsers[1],
    to: mockCurrentUser,
    subject: 'Project update: Q1 roadmap',
    body: 'Hi John,\n\nI wanted to share the Q1 roadmap with you. We are on track with our timeline and the team is doing great work. Let me know if you have any questions.\n\nBest,\nSarah',
    timestamp: new Date(now.getTime() - 2 * 60 * 60 * 1000), // 2 hours ago
    isRead: false,
    isStarred: false,
    isSpam: false,
    labels: [],
    attachments: [],
  },
  {
    id: '2',
    threadId: 'thread-2',
    from: mockUsers[2],
    to: mockCurrentUser,
    subject: 'Meeting notes from Monday',
    body: 'Hi Team,\n\nHere are the notes from our Monday standup:\n- Completed tasks from last sprint\n- New features in progress\n- Blockers and mitigation plans\n\nPlease review and let me know if anything needs clarification.',
    timestamp: new Date(now.getTime() - 3 * 60 * 60 * 1000),
    isRead: false,
    isStarred: false,
    isSpam: false,
    labels: ['2'],
    attachments: [],
  },
  {
    id: '3',
    threadId: 'thread-3',
    from: mockUsers[3],
    to: mockCurrentUser,
    subject: 'Feedback on the design system',
    body: 'John,\n\nI reviewed the new design system components. Great work! A few suggestions:\n1. Consider adding more color variants\n2. Document accessibility requirements\n3. Add interactive examples\n\nLooking forward to the next iteration!',
    timestamp: new Date(now.getTime() - 4 * 60 * 60 * 1000),
    isRead: true,
    isStarred: true,
    isSpam: false,
    labels: ['2', '1'],
    attachments: [],
  },
  {
    id: '4',
    threadId: 'thread-4',
    from: mockUsers[4],
    to: mockCurrentUser,
    subject: 'Client request: urgent site redesign',
    body: 'John,\n\nThe client is requesting an urgent redesign of their website. They want it ready by next Friday. Can we discuss the scope and timeline?\n\nRegards,\nMichael',
    timestamp: new Date(now.getTime() - 6 * 60 * 60 * 1000),
    isRead: false,
    isStarred: false,
    isSpam: false,
    labels: ['1'],
    attachments: [{ id: 'a1', filename: 'design-brief.pdf', size: 2048000, mimeType: 'application/pdf', url: '#' }],
  },
  {
    id: '5',
    threadId: 'thread-5',
    from: mockUsers[5],
    to: mockCurrentUser,
    subject: 'Re: Budget approval for new tools',
    body: 'Hi John,\n\nI wanted to follow up on the budget request for new development tools. The finance team is asking for more details on the ROI. Could you send over a breakdown?\n\nThanks,\nLaura',
    timestamp: new Date(now.getTime() - 8 * 60 * 60 * 1000),
    isRead: true,
    isStarred: false,
    isSpam: false,
    labels: ['2'],
    attachments: [],
  },
  {
    id: '6',
    threadId: 'thread-6',
    from: mockCurrentUser,
    to: mockUsers[1],
    subject: '[Sent] Re: Q1 Planning Session',
    body: 'Hi Sarah,\n\nThanks for sending over the planning session details. I have reviewed everything and it looks great. See you tomorrow at 2 PM.\n\nBest,\nJohn',
    timestamp: new Date(now.getTime() - 12 * 60 * 60 * 1000),
    isRead: true,
    isStarred: false,
    isSpam: false,
    labels: [],
    attachments: [],
  },
  {
    id: '7',
    threadId: 'thread-6',
    from: mockCurrentUser,
    to: mockUsers[1],
    subject: '[Sent] Re: Q1 Planning Session',
    body: 'Hi Sarah,\n\nThanks for sending over the planning session details. I have reviewed everything and it looks great. See you tomorrow at 2 PM.\n\nBest,\nJohn',
    timestamp: new Date(now.getTime() - 12 * 60 * 60 * 1000),
    isRead: true,
    isStarred: false,
    isSpam: false,
    labels: [],
    attachments: [],
  },
]

export const mockThreads: Thread[] = [
  {
    id: 'thread-1',
    userId: mockCurrentUser.id,
    subject: 'Project update: Q1 roadmap',
    participants: [mockUsers[1], mockCurrentUser],
    emails: [mockEmails[0]],
    lastMessageAt: mockEmails[0].timestamp,
    isStarred: false,
    labels: [],
  },
  {
    id: 'thread-2',
    userId: mockCurrentUser.id,
    subject: 'Meeting notes from Monday',
    participants: [mockUsers[2], mockCurrentUser],
    emails: [mockEmails[1]],
    lastMessageAt: mockEmails[1].timestamp,
    isStarred: false,
    labels: ['2'],
  },
  {
    id: 'thread-3',
    userId: mockCurrentUser.id,
    subject: 'Feedback on the design system',
    participants: [mockUsers[3], mockCurrentUser],
    emails: [mockEmails[2]],
    lastMessageAt: mockEmails[2].timestamp,
    isStarred: true,
    labels: ['2', '1'],
  },
  {
    id: 'thread-4',
    userId: mockCurrentUser.id,
    subject: 'Client request: urgent site redesign',
    participants: [mockUsers[4], mockCurrentUser],
    emails: [mockEmails[3]],
    lastMessageAt: mockEmails[3].timestamp,
    isStarred: false,
    labels: ['1'],
  },
  {
    id: 'thread-5',
    userId: mockCurrentUser.id,
    subject: 'Re: Budget approval for new tools',
    participants: [mockUsers[5], mockCurrentUser],
    emails: [mockEmails[4]],
    lastMessageAt: mockEmails[4].timestamp,
    isStarred: false,
    labels: ['2'],
  },
  {
    id: 'thread-6',
    userId: mockCurrentUser.id,
    subject: 'Re: Q1 Planning Session',
    participants: [mockUsers[1], mockCurrentUser],
    emails: [mockEmails[5]],
    lastMessageAt: mockEmails[5].timestamp,
    isStarred: false,
    labels: [],
  },
  {
    id: 'thread-7',
    userId: mockCurrentUser.id,
    subject: 'Re: Q1 Planning Session',
    participants: [mockUsers[1], mockCurrentUser],
    emails: [mockEmails[5]],
    lastMessageAt: mockEmails[5].timestamp,
    isStarred: false,
    labels: [],
  },
]
